name: medal2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2022.10.11
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.15.2
  - ipython=8.6.0
  - jedi=0.18.1
  - jupyter_client=7.4.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - openssl=1.1.1s
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.8.15
  - pyzmq=23.2.0
  - readline=8.2
  - setuptools=65.5.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - absl-py==1.3.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - certifi==2020.6.20
    - cffi==1.15.1
    - chardet==3.0.4
    - click==7.1.2
    - contourpy==1.0.6
    - cycler==0.11.0
    - dataclasses==0.6
    - defusedxml==0.7.1
    - fastjsonschema==2.16.2
    - fasttext==0.9.2
    - filelock==3.0.12
    - fonttools==4.38.0
    - future==0.18.2
    - gensim==3.8.3
    - google-auth==2.15.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.1
    - htmlmin==0.1.12
    - idna==2.10
    - imagehash==4.3.1
    - importlib-metadata==5.1.0
    - importlib-resources==5.10.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-console==6.4.4
    - jupyter-core==5.1.0
    - jupyter-server==1.23.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - lxml==4.9.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - mistune==2.0.4
    - multimethod==1.9
    - nbclassic==0.4.8
    - nbclient==0.7.2
    - nbconvert==7.2.5
    - nbformat==5.7.0
    - networkx==2.8.8
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.22.0
    - oauthlib==3.2.2
    - packaging==20.4
    - pandas==1.1.4
    - pandas-profiling==3.5.0
    - pandocfilters==1.5.0
    - patsy==0.5.3
    - phik==0.12.2
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.4
    - prometheus-client==0.15.0
    - protobuf==3.18.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.10.1
    - pycparser==2.21
    - pydantic==1.10.2
    - pyparsing==2.4.7
    - pyrsistent==0.19.2
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - regex==2020.11.13
    - requests==2.25.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - sacremoses==0.0.43
    - scipy==1.5.4
    - seaborn==0.12.1
    - send2trash==1.8.0
    - sentencepiece==0.1.91
    - six==1.15.0
    - smart-open==3.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - statsmodels==0.13.5
    - tangled-up-in-unicode==0.2.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.17.0
    - tinycss2==1.2.1
    - tokenizers==0.9.3
    - torch==1.7.0
    - tqdm==4.51.0
    - traitlets==5.6.0
    - transformers==3.5.1
    - typeguard==2.13.3
    - typing-extensions==4.4.0
    - urllib3==1.26.5
    - visions==0.7.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - zipp==3.11.0
